services:
  - type: web
    name: image3d-catalog-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: CATALOG_API_KEY
        sync: false
